# Generated by Django 3.1.1 on 2020-09-25 21:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressTable',
            fields=[
                ('address_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'address_table',
            },
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('airline_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('airline_name', models.CharField(max_length=20)),
                ('origin_country', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'airline',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('iata', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.CharField(blank=True, max_length=15, null=True)),
                ('latitude', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'airport',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_card', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('iata', models.ForeignKey(blank=True, db_column='iata', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.airport')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('airline_name', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('departure_airport', models.CharField(blank=True, max_length=5, null=True)),
                ('destination_airport', models.CharField(blank=True, max_length=5, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('destination_time', models.TimeField(blank=True, null=True)),
                ('first_max_seats', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('economy_max_seats', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('airline_code', models.ForeignKey(blank=True, db_column='airline_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.airline')),
                ('flight_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.airport')),
            ],
            options={
                'db_table': 'flight',
            },
        ),
        migrations.CreateModel(
            name='PaymentOptions',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.ForeignKey(blank=True, db_column='email', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.customer')),
            ],
            options={
                'db_table': 'payment_options',
            },
        ),
        migrations.CreateModel(
            name='MilProgram',
            fields=[
                ('program_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('airline_name', models.CharField(blank=True, max_length=20, null=True)),
                ('mileage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('airline_code', models.ForeignKey(blank=True, db_column='airline_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.airline')),
                ('email', models.ForeignKey(blank=True, db_column='email', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.customer')),
            ],
            options={
                'db_table': 'mil_program',
            },
        ),
        migrations.CreateModel(
            name='FlightNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.OneToOneField(db_column='flight_number', on_delete=django.db.models.deletion.DO_NOTHING, to='booking.flight')),
                ('to_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.booking')),
            ],
            options={
                'db_table': 'flight_numbers',
            },
        ),
        migrations.CreateModel(
            name='CreditCardTable',
            fields=[
                ('card_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_card', models.DecimalField(decimal_places=0, max_digits=15)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.paymentoptions')),
            ],
            options={
                'db_table': 'credit_card_table',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.ForeignKey(blank=True, db_column='email', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.creditcardtable'),
        ),
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('billing_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.addresstable')),
                ('credit_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.creditcardtable')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.paymentoptions')),
            ],
            options={
                'db_table': 'billing_info',
            },
        ),
        migrations.AddField(
            model_name='airline',
            name='airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.airport'),
        ),
        migrations.AddField(
            model_name='addresstable',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.paymentoptions'),
        ),
        migrations.AlterUniqueTogether(
            name='airline',
            unique_together={('airline_code', 'airline_name')},
        ),
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('flight_number', models.OneToOneField(db_column='flight_number', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='booking.flight')),
                ('class_type', models.CharField(db_column='class_type', max_length=10)),
                ('email', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, to='booking.customer')),
            ],
            options={
                'db_table': 'booked',
                'unique_together': {('flight_number', 'email', 'class_type')},
            },
        ),
    ]
