# Generated by Django 3.1.1 on 2020-09-30 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='flight_in',
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_airport',
            field=models.ForeignKey(default='ORD', on_delete=django.db.models.deletion.CASCADE, related_name='departure_airport', to='booking.airport'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_airport', to='booking.airport'),
        ),
    ]
