# Generated by Django 3.1.1 on 2020-09-30 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200930_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightnumbers',
            name='flight_number',
        ),
        migrations.RemoveField(
            model_name='flightnumbers',
            name='to_booking',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='credit_card',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment',
        ),
        migrations.AddField(
            model_name='booking',
            name='billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.billinginfo'),
        ),
        migrations.AddField(
            model_name='booking',
            name='class_type',
            field=models.CharField(choices=[('F', 'First Class'), ('E', 'Economy Class')], db_column='class_type', default='E', max_length=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='flight_number',
            field=models.ForeignKey(db_column='flight_number', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.flight'),
        ),
        migrations.DeleteModel(
            name='Booked',
        ),
        migrations.DeleteModel(
            name='FlightNumbers',
        ),
    ]
